<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key'                   => 'group_64eb537eeaaa0',
    'title'                 => __('School info', 'api-schools-manager'),
    'fields'                => array(
       0  => array(
           'key'               => 'field_64f18af6386d6',
           'label'             => __('School type', 'api-schools-manager'),
           'name'              => 'type_of_school',
           'aria-label'        => '',
           'type'              => 'select',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'choices'           => array(
               'pre_school'        => __('Preschool', 'api-schools-manager'),
               'elementary_school' => __('Elementary school', 'api-schools-manager'),
           ),
           'default_value'     => false,
           'return_format'     => 'value',
           'multiple'          => 0,
           'allow_null'        => 0,
           'ui'                => 1,
           'ajax'              => 0,
           'placeholder'       => '',
       ),
       1  => array(
           'key'               => 'field_64eb537fd98b9',
           'label'             => __('Facade images', 'api-schools-manager'),
           'name'              => 'facade_images',
           'aria-label'        => '',
           'type'              => 'gallery',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'return_format'     => 'array',
           'library'           => 'all',
           'min'               => '',
           'max'               => 10,
           'min_width'         => '',
           'min_height'        => '',
           'min_size'          => '',
           'max_width'         => '',
           'max_height'        => '',
           'max_size'          => '',
           'mime_types'        => '',
           'insert'            => 'append',
           'preview_size'      => 'medium',
       ),
       2  => array(
           'key'               => 'field_64f85c7aec4f2',
           'label'             => __('Other Images', 'api-schools-manager'),
           'name'              => 'images',
           'aria-label'        => '',
           'type'              => 'gallery',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'return_format'     => 'array',
           'library'           => 'all',
           'min'               => '',
           'max'               => '',
           'min_width'         => '',
           'min_height'        => '',
           'min_size'          => '',
           'max_width'         => '',
           'max_height'        => '',
           'max_size'          => '',
           'mime_types'        => '',
           'insert'            => 'append',
           'preview_size'      => 'thumbnail',
       ),
       3  => array(
           'key'               => 'field_64f85f1829313',
           'label'             => __('Videos', 'api-schools-manager'),
           'name'              => 'videos',
           'aria-label'        => '',
           'type'              => 'repeater',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'layout'            => 'block',
           'pagination'        => 0,
           'min'               => 0,
           'max'               => 0,
           'collapsed'         => 'field_64f85ca6ec4f4',
           'button_label'      => __('Add video', 'api-schools-manager'),
           'rows_per_page'     => 20,
           'sub_fields'        => array(
               0 => array(
                   'key'               => 'field_64f85f1829314',
                   'label'             => __('Video', 'api-schools-manager'),
                   'name'              => 'url',
                   'aria-label'        => '',
                   'type'              => 'oembed',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'width'             => '',
                   'height'            => '',
                   'parent_repeater'   => 'field_64f85f1829313',
               ),
           ),
       ),
       4  => array(
           'key'               => 'field_64eb5438d98bb',
           'label'             => __('Number of students/children', 'api-schools-manager'),
           'name'              => 'number_of_students',
           'aria-label'        => '',
           'type'              => 'number',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'min'               => '',
           'max'               => '',
           'placeholder'       => '',
           'step'              => '',
           'prepend'           => '',
           'append'            => '',
       ),
       5  => array(
           'key'               => 'field_64eb5479d98bc',
           'label'             => __('Number of units', 'api-schools-manager'),
           'name'              => 'number_of_units',
           'aria-label'        => '',
           'type'              => 'number',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => array(
               0 => array(
                   0 => array(
                       'field'    => 'field_64f18af6386d6',
                       'operator' => '==',
                       'value'    => 'pre_school',
                   ),
               ),
           ),
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'min'               => '',
           'max'               => '',
           'placeholder'       => '',
           'step'              => '',
           'prepend'           => '',
           'append'            => '',
       ),
       6  => array(
           'key'                  => 'field_64eb54e2d98bd',
           'label'                => __('Area', 'api-schools-manager'),
           'name'                 => 'area',
           'aria-label'           => '',
           'type'                 => 'taxonomy',
           'instructions'         => '',
           'required'             => 0,
           'conditional_logic'    => 0,
           'wrapper'              => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'taxonomy'             => 'area',
           'add_term'             => 0,
           'save_terms'           => 1,
           'load_terms'           => 1,
           'return_format'        => 'id',
           'field_type'           => 'select',
           'allow_null'           => 0,
           'bidirectional'        => 0,
           'multiple'             => 0,
           'bidirectional_target' => array(
           ),
       ),
       7  => array(
           'key'                  => 'field_64eb54f8d98be',
           'label'                => __('Grades', 'api-schools-manager'),
           'name'                 => 'grades',
           'aria-label'           => '',
           'type'                 => 'taxonomy',
           'instructions'         => '',
           'required'             => 0,
           'conditional_logic'    => array(
               0 => array(
                   0 => array(
                       'field'    => 'field_64f18af6386d6',
                       'operator' => '==',
                       'value'    => 'elementary_school',
                   ),
               ),
           ),
           'wrapper'              => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'taxonomy'             => 'grade',
           'add_term'             => 0,
           'save_terms'           => 1,
           'load_terms'           => 1,
           'return_format'        => 'id',
           'field_type'           => 'checkbox',
           'bidirectional'        => 0,
           'multiple'             => 0,
           'allow_null'           => 0,
           'bidirectional_target' => array(
           ),
       ),
       8  => array(
           'key'               => 'field_64f6c4b10ecf3',
           'label'             => __('Open hours', 'api-schools-manager'),
           'name'              => 'open_hours',
           'aria-label'        => '',
           'type'              => 'text',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => array(
               0 => array(
                   0 => array(
                       'field'    => 'field_64f18af6386d6',
                       'operator' => '==',
                       'value'    => 'pre_school',
                   ),
               ),
           ),
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'maxlength'         => '',
           'placeholder'       => __('ex. "Vardagar 7:30 - 16"', 'api-schools-manager'),
           'prepend'           => '',
           'append'            => '',
       ),
       9  => array(
           'key'               => 'field_64f1963941741',
           'label'             => __('Open hours (leisure center)', 'api-schools-manager'),
           'name'              => 'open_hours_leisure_center',
           'aria-label'        => '',
           'type'              => 'text',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => array(
               0 => array(
                   0 => array(
                       'field'    => 'field_64f18af6386d6',
                       'operator' => '==',
                       'value'    => 'elementary_school',
                   ),
               ),
           ),
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'maxlength'         => '',
           'placeholder'       => __('ex. "Vardagar 7:30 - 16"', 'api-schools-manager'),
           'prepend'           => '',
           'append'            => '',
       ),
       10 => array(
           'key'               => 'field_64f19467b446c',
           'label'             => __('Specialization', 'api-schools-manager'),
           'name'              => 'specialization',
           'aria-label'        => '',
           'type'              => 'text',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'maxlength'         => '',
           'placeholder'       => '',
           'prepend'           => '',
           'append'            => '',
       ),
       11 => array(
           'key'                  => 'field_64f1970b784f6',
           'label'                => __('Profile', 'api-schools-manager'),
           'name'                 => 'profile',
           'aria-label'           => '',
           'type'                 => 'taxonomy',
           'instructions'         => '',
           'required'             => 0,
           'conditional_logic'    => 0,
           'wrapper'              => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'taxonomy'             => 'profile',
           'add_term'             => 1,
           'save_terms'           => 1,
           'load_terms'           => 1,
           'return_format'        => 'id',
           'field_type'           => 'multi_select',
           'allow_null'           => 1,
           'bidirectional'        => 0,
           'multiple'             => 0,
           'bidirectional_target' => array(
           ),
       ),
       12 => array(
           'key'               => 'field_64f198b7c71ba',
           'label'             => __('Own chef', 'api-schools-manager'),
           'name'              => 'own_chef',
           'aria-label'        => '',
           'type'              => 'true_false',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '50',
               'class' => '',
               'id'    => '',
           ),
           'message'           => '',
           'default_value'     => 0,
           'ui_on_text'        => '',
           'ui_off_text'       => '',
           'ui'                => 1,
       ),
       13 => array(
           'key'               => 'field_64f198f6c71bb',
           'label'             => __('Own library', 'api-schools-manager'),
           'name'              => 'own_library',
           'aria-label'        => '',
           'type'              => 'true_false',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '50',
               'class' => '',
               'id'    => '',
           ),
           'message'           => '',
           'default_value'     => 0,
           'ui_on_text'        => '',
           'ui_off_text'       => '',
           'ui'                => 1,
       ),
       14 => array(
           'key'               => 'field_64f1abedcbdf8',
           'label'             => __('Link Instagram', 'api-schools-manager'),
           'name'              => 'link_instagram',
           'aria-label'        => '',
           'type'              => 'url',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'placeholder'       => '',
       ),
       15 => array(
           'key'               => 'field_64f1ac0bcbdf9',
           'label'             => __('Link Facebook', 'api-schools-manager'),
           'name'              => 'link_facebook',
           'aria-label'        => '',
           'type'              => 'url',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'placeholder'       => '',
       ),
       16 => array(
           'key'               => 'field_64fed7664e639',
           'label'             => __('Custom excerpt', 'api-schools-manager'),
           'name'              => 'custom_excerpt',
           'aria-label'        => '',
           'type'              => 'wysiwyg',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'default_value'     => '',
           'tabs'              => 'all',
           'toolbar'           => 'basic',
           'media_upload'      => 0,
           'delay'             => 0,
       ),
       17 => array(
           'key'               => 'field_64f19916c71bc',
           'label'             => __('Information', 'api-schools-manager'),
           'name'              => 'information',
           'aria-label'        => '',
           'type'              => 'group',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'layout'            => 'block',
           'sub_fields'        => array(
               0 => array(
                   'key'               => 'field_64f60e4f396e7',
                   'label'             => __('About Us', 'api-schools-manager'),
                   'name'              => '',
                   'aria-label'        => '',
                   'type'              => 'accordion',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'open'              => 0,
                   'multi_expand'      => 1,
                   'endpoint'          => 0,
               ),
               1 => array(
                   'key'               => 'field_64f19a40c71be',
                   'label'             => '',
                   'name'              => 'about_us',
                   'aria-label'        => '',
                   'type'              => 'wysiwyg',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => array(
                       0 => array(
                           0 => array(
                               'field'    => 'field_64f18af6386d6',
                               'operator' => '!=empty',
                           ),
                       ),
                   ),
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'default_value'     => '',
                   'tabs'              => 'all',
                   'toolbar'           => 'basic',
                   'media_upload'      => 0,
                   'delay'             => 0,
               ),
               2 => array(
                   'key'               => 'field_64f60e77396e8',
                   'label'             => __('How we work', 'api-schools-manager'),
                   'name'              => '',
                   'aria-label'        => '',
                   'type'              => 'accordion',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'open'              => 0,
                   'multi_expand'      => 1,
                   'endpoint'          => 0,
               ),
               3 => array(
                   'key'               => 'field_64f19b0dc71c0',
                   'label'             => '',
                   'name'              => 'how_we_work',
                   'aria-label'        => '',
                   'type'              => 'wysiwyg',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'default_value'     => '',
                   'tabs'              => 'all',
                   'toolbar'           => 'basic',
                   'media_upload'      => 0,
                   'delay'             => 0,
               ),
               4 => array(
                   'key'               => 'field_64f60e82396e9',
                   'label'             => __('Optional rows', 'api-schools-manager'),
                   'name'              => '',
                   'aria-label'        => '',
                   'type'              => 'accordion',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'open'              => 0,
                   'multi_expand'      => 1,
                   'endpoint'          => 0,
               ),
               5 => array(
                   'key'               => 'field_64f19b20c71c1',
                   'label'             => '',
                   'name'              => 'optional',
                   'aria-label'        => '',
                   'type'              => 'repeater',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'layout'            => 'block',
                   'pagination'        => 0,
                   'min'               => 0,
                   'max'               => 0,
                   'collapsed'         => 'field_64f19b8bc71c3',
                   'button_label'      => __('Lägg till', 'api-schools-manager'),
                   'rows_per_page'     => 20,
                   'sub_fields'        => array(
                       0 => array(
                           'key'               => 'field_64f19b8bc71c3',
                           'label'             => __('Heading', 'api-schools-manager'),
                           'name'              => 'heading',
                           'aria-label'        => '',
                           'type'              => 'text',
                           'instructions'      => '',
                           'required'          => 0,
                           'conditional_logic' => 0,
                           'wrapper'           => array(
                               'width' => '',
                               'class' => '',
                               'id'    => '',
                           ),
                           'default_value'     => '',
                           'maxlength'         => '',
                           'placeholder'       => '',
                           'prepend'           => '',
                           'append'            => '',
                           'parent_repeater'   => 'field_64f19b20c71c1',
                       ),
                       1 => array(
                           'key'               => 'field_64f19b75c71c2',
                           'label'             => __('Content', 'api-schools-manager'),
                           'name'              => 'content',
                           'aria-label'        => '',
                           'type'              => 'wysiwyg',
                           'instructions'      => '',
                           'required'          => 0,
                           'conditional_logic' => 0,
                           'wrapper'           => array(
                               'width' => '',
                               'class' => '',
                               'id'    => '',
                           ),
                           'default_value'     => '',
                           'tabs'              => 'all',
                           'toolbar'           => 'basic',
                           'media_upload'      => 0,
                           'delay'             => 0,
                           'parent_repeater'   => 'field_64f19b20c71c1',
                       ),
                   ),
               ),
           ),
       ),
       18 => array(
           'key'               => 'field_64f6c13a6c30b',
           'label'             => __('Visiting address', 'api-schools-manager'),
           'name'              => 'visiting_address',
           'aria-label'        => '',
           'type'              => 'repeater',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'layout'            => 'block',
           'pagination'        => 0,
           'min'               => 1,
           'max'               => 0,
           'collapsed'         => 'field_64f6bff16c30a',
           'button_label'      => __('Add additional addresses', 'api-schools-manager'),
           'rows_per_page'     => 20,
           'sub_fields'        => array(
               0 => array(
                   'key'               => 'field_64f6bff16c30a',
                   'label'             => __('Address', 'api-schools-manager'),
                   'name'              => 'address',
                   'aria-label'        => '',
                   'type'              => 'google_map',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'center_lat'        => '56.043398530874754',
                   'center_lng'        => '12.707579121882867',
                   'zoom'              => '',
                   'height'            => 200,
                   'parent_repeater'   => 'field_64f6c13a6c30b',
               ),
           ),
       ),
       19 => array(
           'key'               => 'field_64f6c5b50ecf4',
           'label'             => __('Contacts', 'api-schools-manager'),
           'name'              => 'contacts',
           'aria-label'        => '',
           'type'              => 'repeater',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'layout'            => 'row',
           'pagination'        => 0,
           'min'               => 0,
           'max'               => 0,
           'collapsed'         => 'field_64f6c6760ecf5',
           'button_label'      => __('Add contact', 'api-schools-manager'),
           'rows_per_page'     => 20,
           'sub_fields'        => array(
               0 => array(
                   'key'                  => 'field_64f6c7160ecf7',
                   'label'                => __('Professional title', 'api-schools-manager'),
                   'name'                 => 'professional_title',
                   'aria-label'           => '',
                   'type'                 => 'taxonomy',
                   'instructions'         => '',
                   'required'             => 0,
                   'conditional_logic'    => 0,
                   'wrapper'              => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'taxonomy'             => 'professional_title',
                   'add_term'             => 0,
                   'save_terms'           => 0,
                   'load_terms'           => 0,
                   'return_format'        => 'object',
                   'field_type'           => 'select',
                   'allow_null'           => 1,
                   'bidirectional'        => 0,
                   'multiple'             => 0,
                   'bidirectional_target' => array(
                   ),
                   'parent_repeater'      => 'field_64f6c5b50ecf4',
               ),
               1 => array(
                   'key'                  => 'field_64f6c6760ecf5',
                   'label'                => __('Person', 'api-schools-manager'),
                   'name'                 => 'person',
                   'aria-label'           => '',
                   'type'                 => 'post_object',
                   'instructions'         => '',
                   'required'             => 0,
                   'conditional_logic'    => 0,
                   'wrapper'              => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'post_type'            => array(
                       0 => 'person',
                   ),
                   'post_status'          => array(
                       0 => 'publish',
                   ),
                   'taxonomy'             => '',
                   'return_format'        => 'object',
                   'multiple'             => 0,
                   'allow_null'           => 0,
                   'bidirectional'        => 0,
                   'ui'                   => 1,
                   'bidirectional_target' => array(
                   ),
                   'parent_repeater'      => 'field_64f6c5b50ecf4',
               ),
           ),
       ),
       20 => array(
           'key'               => 'field_64faa70961cb9',
           'label'             => __('Call to action: Application', 'api-schools-manager'),
           'name'              => '',
           'aria-label'        => '',
           'type'              => 'accordion',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'open'              => 0,
           'multi_expand'      => 0,
           'endpoint'          => 0,
       ),
       21 => array(
           'key'               => 'field_64faa512774db',
           'label'             => '',
           'name'              => 'cta_application',
           'aria-label'        => '',
           'type'              => 'group',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'layout'            => 'block',
           'sub_fields'        => array(
               0 => array(
                   'key'               => 'field_64faa62f774de',
                   'label'             => __('Description', 'api-schools-manager'),
                   'name'              => 'description',
                   'aria-label'        => '',
                   'type'              => 'text',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '',
                       'class' => '',
                       'id'    => '',
                   ),
                   'default_value'     => '',
                   'maxlength'         => '',
                   'placeholder'       => '',
                   'prepend'           => '',
                   'append'            => '',
               ),
               1 => array(
                   'key'               => 'field_64faa55e774dc',
                   'label'             => __('Apply here', 'api-schools-manager'),
                   'name'              => 'cta_apply_here',
                   'aria-label'        => '',
                   'type'              => 'link',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '50',
                       'class' => '',
                       'id'    => '',
                   ),
                   'return_format'     => 'array',
               ),
               2 => array(
                   'key'               => 'field_64faa5e6774dd',
                   'label'             => __('How to apply', 'api-schools-manager'),
                   'name'              => 'cta_how_to_apply',
                   'aria-label'        => '',
                   'type'              => 'link',
                   'instructions'      => '',
                   'required'          => 0,
                   'conditional_logic' => 0,
                   'wrapper'           => array(
                       'width' => '50',
                       'class' => '',
                       'id'    => '',
                   ),
                   'return_format'     => 'array',
               ),
           ),
       ),
       22 => array(
           'key'               => 'field_64faa7b7c1982',
           'label'             => __('end call to action accordion', 'api-schools-manager'),
           'name'              => '',
           'aria-label'        => '',
           'type'              => 'accordion',
           'instructions'      => '',
           'required'          => 0,
           'conditional_logic' => 0,
           'wrapper'           => array(
               'width' => '',
               'class' => '',
               'id'    => '',
           ),
           'open'              => 0,
           'multi_expand'      => 0,
           'endpoint'          => 1,
       ),
    ),
    'location'              => array(
       0 => array(
           0 => array(
               'param'    => 'post_type',
               'operator' => '==',
               'value'    => 'school',
           ),
       ),
    ),
    'menu_order'            => 0,
    'position'              => 'side',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => '',
    'show_in_rest'          => 1,
    ));
}
